name: 'JIRA integration'
description: 'JIRA integration'
inputs:
  github-token:
    description: 'Token used to update PR description and add labels. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  jira-username:
    description: 'Username (or email) used to access the JIRA REST API. Must have read access to your JIRA Projects & Issues.'
    required: true
  jira-token:
    description: 'API Token used to access the JIRA REST API. Must belong to <jira-username>.'
    required: true
  jira-base-url:
    description: 'The subdomain of JIRA cloud that you use to access it. Ex: "https://your-domain.atlassian.net".'
    required: true
  jira-project-key-regexp:
    description: "Regexp referenced JIRA issue's code project key should match."
    required: false
    default: ''

  pr-enforce-issue-exists:
    description: 'Whether to enforce JIRA issue codes existence in PR title.'
    required: false
    default: 'true'
  pr-enforce-issue-type-regexp:
    description: "Regexp JIRA issue's type to match a regular expression (ie '^epic$')."
    required: false
    default: ''
  pr-update-title:
    description: 'Whether to update PR title with JIRA issue summary.'
    required: false
    default: 'true'
  pr-update-description:
    description: 'Whether to update PR body to include JIRA issue description.'
    required: false
    default: 'true'
  pr-issue-code-regexp:
    description: 'Regexp used to match JIRA issue code in PR title.'
    required: false
    default: '^\[(\w+[_-]\d+)\]'
  pr-skip-base-ref-regexp:
    description: 'Skip checks for PRs with a base ref matching this regexp (target ref: ie "^deploy/").'
    required: false
    default: ''
  pr-skip-head-ref-regexp:
    description: 'Skip checks for PRs with a head ref matching this regexp (source ref: ie "^main$", "^hotfix/", "^(main|hotfix/.*)$").'
    required: false
    default: ''
  pr-skip-user-regexp:
    description: 'Skip checks when PR user matches this regexp (ie "^dimvic$").'
    required: false
    default: ''

  #  enforce-code-branch:
  #    description: 'Whether to enforce branch name to include mentioned in PR title.'
  #    required: false
  #    default: 'false'
  #  branch-issue-regexp:
  #    description: 'Regexp used to match JIRA issue code in branch name.'
  #    required: false
  #    default: '^\\w+[_-]\d+'

runs:
  using: 'node16'
  main: 'index.js'
